name: make release
on:
  push:
    branches:
      - master
jobs:
  release:
    permissions:
      contents: write
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: install dependencies
        run: sudo apt-get install minify zip

      - name: Build
        run: make release

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: "prerelease-v${{ github.run_number }}"
          name: "Pre-Release v${{ github.run_number }}"
          body: "Automated release created by GitHub Actions."
          draft: false
          prerelease: true
          allowUpdates: true
          artifacts: "u64-better-webinterface.zip"
